# Generated by Django 4.1.5 on 2023-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('food_name', models.TextField(max_length=300)),
                ('food_price', models.IntegerField()),
                ('food_available', models.BooleanField(default=False)),
                ('food_image', models.ImageField(default='', upload_to='static/images/')),
            ],
        ),
    ]
